spring:
  application:
    name: hibernate6issue
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
