services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'jpaspec@acme.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
      PGADMIN_LISTEN_PORT: '80'
    ports:
      - '15432:80'
    depends_on:
      - 'postgres'